# Example configuration file for using DynamoDB as primary database
# Copy this to user_data/config.toml and modify as needed

# Database configuration
[database]
type = "dynamodb"  # Use "sqlite" for SQLite, "dynamodb" for DynamoDB

[database.sqlite]
# SQLite configuration (used as backup when DynamoDB is primary)
# path = "/custom/path/to/database.db"  # Optional: custom path, uses default if not specified

[database.dynamodb]
region = "us-west-2"  # AWS region where DynamoDB tables are located

# LLM Provider configurations
[anthropic]
models = { "claude-3-7-sonnet-latest" = { type = "text" } }
url = "https://api.anthropic.com/v1/"
api_key = "your-anthropic-api-key"
max_tokens = 8192

[openai]
models = { 
    "gpt-4o" = { type = "text" }, 
    "gpt-4o-mini" = { type = "text" },
    "gpt-image-1" = { type = "image" }
}
url = "https://api.openai.com/v1/"
api_key = "your-openai-api-key"
max_tokens = 8192

[bedrock]
models = { 
    "us.anthropic.claude-3-7-sonnet-20250219-v1:0" = { type = "text" },
    "us.anthropic.claude-3-5-sonnet-20241022-v2:0" = { type = "text" },
    "us.anthropic.claude-3-5-haiku-20241022-v1:0" = { type = "text" }
}
url = ""
api_key = ""  # Not needed for Bedrock - uses AWS credentials
max_tokens = 8192
region = "us-west-2"

[comfyui]
models = { 
    "flux-kontext" = { type = "image" },
    "flux-t2i" = { type = "image" }
}
url = "http://comfyui-alb-905118004.us-west-2.elb.amazonaws.com:8080"
api_key = ""
